### ISSUE TITLE
Promisified version of utimes

### ISSUE THREAD

**Issue by kachkaev** [ronomon/utimes#2]
Hi @ronomon, many thanks for this useful utility! I'm happy that I've discovered utimes; playing with it now 👍 

A quick thought: how about supporting Promises, i.e. make utimes return a promise when no callback is provided? My current workaround looks like this, not sure if it's 100% correct.

```js
const utimesPromise = (path, btime, mtime, atime) =>
  new Promise((resolve, reject) => {
    utimes(path, btime, mtime, atime, (err) => (err ? reject(err) : resolve()));
  });

// ...
await utimesPromise(myPath, myBtime);
```

**Comment by jorangreef** [comment]
Thanks @kachkaev!

We don't use promises at Ronomon for several reasons, but you can always wrap `@ronomon/utimes` yourself to return a promise if you really need to.

**Comment by soubhikchatterjee** [comment]
@jorangreef 

Are there any disadvantages if we wrap **_`@ronomon/utimes`_** to return a promise?

**Comment by jorangreef** [comment]
It depends on the performance requirements you have. If you're not sure, it's probably fine.

I think pure callbacks are simpler, less complicated, and easier to get right, but people new to Javascript coming from other languages tend to prefer promises.

**Comment by kachkaev** [comment]
> People new to Javascript coming from other languages tend to prefer promises

Not sure I can agree with this statement in 2019 given the prevalence of async / await syntax and the decent performance of native promises in Node 10+.

> It depends on the performance requirements you have

Perhaps, if the choice between a promise and a callback is critical performance-wise, JavaScript is not the right language for the chunk of code you use utimes in.

Having said that, I respect your choice to not add promises to utimes ;–) Thanks for creating this useful library!

**Comment by jorangreef** [comment]
Thanks @kachkaev 

Sure, the performance of promises has improved. I think you'd agree with me that I'm not sure it's on par with pure callbacks, not just from a CPU point of view, but also taking memory allocations and GC pressure into account. These add up when you're writing large JS applications.

Of course, this is just a utimes library, but we have several modules such as [@ronomon/hash-table](https://github.com/ronomon/hash-table), and [@ronomon/crypto-async](https://github.com/ronomon/crypto-async), which are performance critical and where we would avoid promises like the plague. JS is a great language, as a scripting language it can be ridiculously fast (within 30% of C), if you stick to the fast-lane and avoid exotic features.

Personally, I don't think the "always use Promises" mantra is healthy for developers, which is why I try to teach the difference whenever I can. I don't see much ergonomic difference, except that promisified code tends to more exception handling which I find more awkward than callback hell. Of course, using callbacks does not necessarily imply callback hell. I personally prefer seeing the asynchronicity of code, rather than making it look synchronous when it's not.

Having said that, as you say, I respect your choice to use promises. And thanks for letting me keep this library "plain and simple" without promises! ;-)
